lmotel helm chart fixes and improvements
logicmonitor/k8s-helm-charts pull request #120
Opened 2022-04-27 11:34 UTC by avadhut123pisal

1.  Fix ingress resource API version incompatibility issues.
2. Allow input of the TLS secret for the ingress resources.
3. Allow input of the ingress resource-specific annotations.
4. Fix the HTTP route from the ingress-http resource.

2022-05-02 13:09 UTC, vkumbhar94 approved these changes

2022-05-04 05:18 UTC, vkumbhar94 requested changes
please check index.yaml and resolve comments, as it has conflict marks in it

Please run `make` on your branch and commit the generated files.

2022-05-04 05:59 UTC, avadhut123pisal commented
> please check index.yaml and resolve comments, as it has conflict marks in it
> 
> Please run `make` on your branch and commit the generated files.

The requested changes are done.

2022-05-04 06:09 UTC, vkumbhar94 approved these changes

2022-05-04 06:15 UTC, merged