PR for lm-logs-release-0.3.3
logicmonitor/k8s-helm-charts pull request #140
Opened 2022-10-20 07:42 UTC by choudharypooja

PR for ticket https://jira.logicmonitor.com/browse/DEV-111918

2022-10-20 08:59 UTC, shubhashri12 approved these changes

2022-10-20 09:25 UTC, ashishkucheria approved these changes

2022-10-20 10:26 UTC, ahsan13jan commented on lm-logs/values.yaml
> +  multiline_start_regexp: /^\[(\d{4}-)?\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}.*\]/
We should not keep a default, It is upon customer to customer what they want to add it as.

2022-10-20 10:27 UTC, ahsan13jan commented on lm-logs/templates/configmap.yaml
> +
What is the customer does want this multiline start regex, what if it wants use the default `\n`?

2022-10-20 10:29 UTC, ahsan13jan requested changes
We should not default it to use the multiline logs plugin, if the customer wants it they can add it,

2022-10-27 13:21 UTC, ahsan13jan approved these changes

2022-10-28 00:46 UTC, vkumbhar94 requested changes
seems you have built chart before bumping up the version, hence docs/lm-logs-0.3.2.tgz is showing in diff

2022-10-28 06:25 UTC, siddharthck approved these changes

2022-10-31 05:14 UTC, vkumbhar94 approved these changes

2022-10-31 06:36 UTC, merged